# Generated by Django 2.0.5 on 2018-05-08 17:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dzielnica',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('teryt', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=2180)),
            ],
        ),
    ]
