# Generated by Django 2.0.5 on 2018-05-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Użytkownik',
                'verbose_name_plural': 'Użytkownicy',
            },
        ),
        migrations.AlterModelOptions(
            name='dzielnica',
            options={'verbose_name': 'Dzielnica', 'verbose_name_plural': 'Dzielnice'},
        ),
        migrations.AlterField(
            model_name='dzielnica',
            name='gid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
